import type { Metadata } from "next";
import "./globals.css";
import LightRays from "@/components/ui/LightRays";
import { Navbar, Footer } from "@/components/pages/index";

export const metadata: Metadata = {
  title: "Next JS Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative min-h-screen flex flex-col">
        <Navbar />

        <div className="absolute inset-0 z-[-1] min-h-screen">
          <LightRays
            raysColor="#5dfeca"
            raysSpeed={1.5}
            lightSpread={0.8}
            rayLength={1.2}
            followMouse
            mouseInfluence={0.1}
            noiseAmount={0.1}
            distortion={0.05}
          />
        </div>
        <main className="flex-1">{children}</main>
      <Footer />
      </body>
    </html>
  );
}
